DSN: "host=localhost port=5432 user=nir dbname=freelancers password=12qwaszx sslmode=disable"
Mode: debug # debug / release

jwt:
  verification_key: "QfCAH04Cob7b71QCqy738vw5XGSnFZ9d"
  signing_key: "QfCAH04Cob7b71QCqy738vw5XGSnFZ9d"